CREATE TABLE [dbo].[Prices]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Id_Transporter] INT NOT NULL, 
    [LaneName] NVARCHAR(200) NOT NULL, 
    [Id_OriginCountry] INT NOT NULL, 
    [Id_OriginCity] INT NOT NULL, 
    [Id_OriginZip] INT NOT NULL, 
    [Id_DestinationCountry] INT NOT NULL, 
    [Id_DestinationCity] INT NOT NULL, 
    [Id_DestinationZip] INT NOT NULL, 
    [Id_RequestType] INT NOT NULL, 
    [Id_PartnerLocation] INT NOT NULL, 
    [Minimum] MONEY NOT NULL, 
    [From1To4Pallets] MONEY NOT NULL, 
    [From5To8Pallets] MONEY NOT NULL, 
    [From9To12Pallets] MONEY NOT NULL, 
    [From13To16Pallets] MONEY NOT NULL, 
    [From17To20Pallets] MONEY NOT NULL, 
    [From21To24Pallets] MONEY NOT NULL, 
    [From25To28Pallets] MONEY NOT NULL, 
    [From29To32Pallets] MONEY NOT NULL, 
    [From33To36Pallets] MONEY NOT NULL, 
    [From37To40Pallets] MONEY NOT NULL, 
    [From41To44Pallets] MONEY NOT NULL, 
    [From45To48Pallets] MONEY NOT NULL, 
    [From49To52Pallets] MONEY NOT NULL, 
    [From53To56Pallets] MONEY NOT NULL, 
    [From57To60Pallets] MONEY NOT NULL, 
    [From61To64Pallets] MONEY NOT NULL, 
    [Maximum] MONEY NOT NULL, 
    [ShipmentFrequencyLTL] NVARCHAR(50) NOT NULL, 
    [TransitTimeGroupage] INT NOT NULL, 
    [TransitTimeLTL] INT NOT NULL, 
    [CommentsLTL] NVARCHAR(100) NULL, 
    [Tons3_5] MONEY NOT NULL, 
    [TransitTime3_5Tons] INT NOT NULL, 
    [ShipmentFrequency3_5Tons] NVARCHAR(50) NOT NULL, 
    [Tons7_5] MONEY NOT NULL, 
    [ShipmentFrequency7_5Tons] NVARCHAR(50) NOT NULL, 
    [Tons24] MONEY NOT NULL, 
    [ShipmentFrequency24Tons] NVARCHAR(50) NOT NULL, 
    [TransitTimeFTL] INT NOT NULL, 
    [CommentsFTL] NVARCHAR(100) NULL, 
    [Active] INT NOT NULL
)
