#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleImportExcelPrices
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IOToolData")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCity(City instance);
    partial void UpdateCity(City instance);
    partial void DeleteCity(City instance);
    partial void InsertCountry(Country instance);
    partial void UpdateCountry(Country instance);
    partial void DeleteCountry(Country instance);
    partial void InsertPrice(Price instance);
    partial void UpdatePrice(Price instance);
    partial void DeletePrice(Price instance);
    partial void InsertPricesImport(PricesImport instance);
    partial void UpdatePricesImport(PricesImport instance);
    partial void DeletePricesImport(PricesImport instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleImportExcelPrices.Properties.Settings.Default.IOToolDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<City> Cities
		{
			get
			{
				return this.GetTable<City>();
			}
		}
		
		public System.Data.Linq.Table<Country> Countries
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
		
		public System.Data.Linq.Table<Price> Prices
		{
			get
			{
				return this.GetTable<Price>();
			}
		}
		
		public System.Data.Linq.Table<PricesImport> PricesImports
		{
			get
			{
				return this.GetTable<PricesImport>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cities")]
	public partial class City : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private int _Id_Country;
		
		private int _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnId_CountryChanging(int value);
    partial void OnId_CountryChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    #endregion
		
		public City()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Country", DbType="Int NOT NULL")]
		public int Id_Country
		{
			get
			{
				return this._Id_Country;
			}
			set
			{
				if ((this._Id_Country != value))
				{
					this.OnId_CountryChanging(value);
					this.SendPropertyChanging();
					this._Id_Country = value;
					this.SendPropertyChanged("Id_Country");
					this.OnId_CountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Countries")]
	public partial class Country : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Code;
		
		private int _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    #endregion
		
		public Country()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Prices")]
	public partial class Price : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _Id_Transporter;
		
		private string _LaneName;
		
		private int _Id_OriginCountry;
		
		private int _Id_OriginCity;
		
		private int _Id_OriginZip;
		
		private int _Id_DestinationCountry;
		
		private int _Id_DestinationCity;
		
		private int _Id_DestinationZip;
		
		private int _Id_RequestType;
		
		private int _Id_PartnerLocation;
		
		private decimal _Minimum;
		
		private decimal _From1To4Pallets;
		
		private decimal _From5To8Pallets;
		
		private decimal _From9To12Pallets;
		
		private decimal _From13To16Pallets;
		
		private decimal _From17To20Pallets;
		
		private decimal _From21To24Pallets;
		
		private decimal _From25To28Pallets;
		
		private decimal _From29To32Pallets;
		
		private decimal _From33To36Pallets;
		
		private decimal _From37To40Pallets;
		
		private decimal _From41To44Pallets;
		
		private decimal _From45To48Pallets;
		
		private decimal _From49To52Pallets;
		
		private decimal _From53To56Pallets;
		
		private decimal _From57To60Pallets;
		
		private decimal _From61To64Pallets;
		
		private decimal _Maximum;
		
		private string _ShipmentFrequencyLTL;
		
		private int _TransitTimeGroupage;
		
		private int _TransitTimeLTL;
		
		private string _CommentsLTL;
		
		private decimal _Tons3_5;
		
		private int _TransitTime3_5Tons;
		
		private string _ShipmentFrequency3_5Tons;
		
		private decimal _Tons7_5;
		
		private string _ShipmentFrequency7_5Tons;
		
		private decimal _Tons24;
		
		private string _ShipmentFrequency24Tons;
		
		private int _TransitTimeFTL;
		
		private string _CommentsFTL;
		
		private int _Active;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnId_TransporterChanging(int value);
    partial void OnId_TransporterChanged();
    partial void OnLaneNameChanging(string value);
    partial void OnLaneNameChanged();
    partial void OnId_OriginCountryChanging(int value);
    partial void OnId_OriginCountryChanged();
    partial void OnId_OriginCityChanging(int value);
    partial void OnId_OriginCityChanged();
    partial void OnId_OriginZipChanging(int value);
    partial void OnId_OriginZipChanged();
    partial void OnId_DestinationCountryChanging(int value);
    partial void OnId_DestinationCountryChanged();
    partial void OnId_DestinationCityChanging(int value);
    partial void OnId_DestinationCityChanged();
    partial void OnId_DestinationZipChanging(int value);
    partial void OnId_DestinationZipChanged();
    partial void OnId_RequestTypeChanging(int value);
    partial void OnId_RequestTypeChanged();
    partial void OnId_PartnerLocationChanging(int value);
    partial void OnId_PartnerLocationChanged();
    partial void OnMinimumChanging(decimal value);
    partial void OnMinimumChanged();
    partial void OnFrom1To4PalletsChanging(decimal value);
    partial void OnFrom1To4PalletsChanged();
    partial void OnFrom5To8PalletsChanging(decimal value);
    partial void OnFrom5To8PalletsChanged();
    partial void OnFrom9To12PalletsChanging(decimal value);
    partial void OnFrom9To12PalletsChanged();
    partial void OnFrom13To16PalletsChanging(decimal value);
    partial void OnFrom13To16PalletsChanged();
    partial void OnFrom17To20PalletsChanging(decimal value);
    partial void OnFrom17To20PalletsChanged();
    partial void OnFrom21To24PalletsChanging(decimal value);
    partial void OnFrom21To24PalletsChanged();
    partial void OnFrom25To28PalletsChanging(decimal value);
    partial void OnFrom25To28PalletsChanged();
    partial void OnFrom29To32PalletsChanging(decimal value);
    partial void OnFrom29To32PalletsChanged();
    partial void OnFrom33To36PalletsChanging(decimal value);
    partial void OnFrom33To36PalletsChanged();
    partial void OnFrom37To40PalletsChanging(decimal value);
    partial void OnFrom37To40PalletsChanged();
    partial void OnFrom41To44PalletsChanging(decimal value);
    partial void OnFrom41To44PalletsChanged();
    partial void OnFrom45To48PalletsChanging(decimal value);
    partial void OnFrom45To48PalletsChanged();
    partial void OnFrom49To52PalletsChanging(decimal value);
    partial void OnFrom49To52PalletsChanged();
    partial void OnFrom53To56PalletsChanging(decimal value);
    partial void OnFrom53To56PalletsChanged();
    partial void OnFrom57To60PalletsChanging(decimal value);
    partial void OnFrom57To60PalletsChanged();
    partial void OnFrom61To64PalletsChanging(decimal value);
    partial void OnFrom61To64PalletsChanged();
    partial void OnMaximumChanging(decimal value);
    partial void OnMaximumChanged();
    partial void OnShipmentFrequencyLTLChanging(string value);
    partial void OnShipmentFrequencyLTLChanged();
    partial void OnTransitTimeGroupageChanging(int value);
    partial void OnTransitTimeGroupageChanged();
    partial void OnTransitTimeLTLChanging(int value);
    partial void OnTransitTimeLTLChanged();
    partial void OnCommentsLTLChanging(string value);
    partial void OnCommentsLTLChanged();
    partial void OnTons3_5Changing(decimal value);
    partial void OnTons3_5Changed();
    partial void OnTransitTime3_5TonsChanging(int value);
    partial void OnTransitTime3_5TonsChanged();
    partial void OnShipmentFrequency3_5TonsChanging(string value);
    partial void OnShipmentFrequency3_5TonsChanged();
    partial void OnTons7_5Changing(decimal value);
    partial void OnTons7_5Changed();
    partial void OnShipmentFrequency7_5TonsChanging(string value);
    partial void OnShipmentFrequency7_5TonsChanged();
    partial void OnTons24Changing(decimal value);
    partial void OnTons24Changed();
    partial void OnShipmentFrequency24TonsChanging(string value);
    partial void OnShipmentFrequency24TonsChanged();
    partial void OnTransitTimeFTLChanging(int value);
    partial void OnTransitTimeFTLChanged();
    partial void OnCommentsFTLChanging(string value);
    partial void OnCommentsFTLChanged();
    partial void OnActiveChanging(int value);
    partial void OnActiveChanged();
    #endregion
		
		public Price()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_Transporter", DbType="Int NOT NULL")]
		public int Id_Transporter
		{
			get
			{
				return this._Id_Transporter;
			}
			set
			{
				if ((this._Id_Transporter != value))
				{
					this.OnId_TransporterChanging(value);
					this.SendPropertyChanging();
					this._Id_Transporter = value;
					this.SendPropertyChanged("Id_Transporter");
					this.OnId_TransporterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string LaneName
		{
			get
			{
				return this._LaneName;
			}
			set
			{
				if ((this._LaneName != value))
				{
					this.OnLaneNameChanging(value);
					this.SendPropertyChanging();
					this._LaneName = value;
					this.SendPropertyChanged("LaneName");
					this.OnLaneNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_OriginCountry", DbType="Int NOT NULL")]
		public int Id_OriginCountry
		{
			get
			{
				return this._Id_OriginCountry;
			}
			set
			{
				if ((this._Id_OriginCountry != value))
				{
					this.OnId_OriginCountryChanging(value);
					this.SendPropertyChanging();
					this._Id_OriginCountry = value;
					this.SendPropertyChanged("Id_OriginCountry");
					this.OnId_OriginCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_OriginCity", DbType="Int NOT NULL")]
		public int Id_OriginCity
		{
			get
			{
				return this._Id_OriginCity;
			}
			set
			{
				if ((this._Id_OriginCity != value))
				{
					this.OnId_OriginCityChanging(value);
					this.SendPropertyChanging();
					this._Id_OriginCity = value;
					this.SendPropertyChanged("Id_OriginCity");
					this.OnId_OriginCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_OriginZip", DbType="Int NOT NULL")]
		public int Id_OriginZip
		{
			get
			{
				return this._Id_OriginZip;
			}
			set
			{
				if ((this._Id_OriginZip != value))
				{
					this.OnId_OriginZipChanging(value);
					this.SendPropertyChanging();
					this._Id_OriginZip = value;
					this.SendPropertyChanged("Id_OriginZip");
					this.OnId_OriginZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DestinationCountry", DbType="Int NOT NULL")]
		public int Id_DestinationCountry
		{
			get
			{
				return this._Id_DestinationCountry;
			}
			set
			{
				if ((this._Id_DestinationCountry != value))
				{
					this.OnId_DestinationCountryChanging(value);
					this.SendPropertyChanging();
					this._Id_DestinationCountry = value;
					this.SendPropertyChanged("Id_DestinationCountry");
					this.OnId_DestinationCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DestinationCity", DbType="Int NOT NULL")]
		public int Id_DestinationCity
		{
			get
			{
				return this._Id_DestinationCity;
			}
			set
			{
				if ((this._Id_DestinationCity != value))
				{
					this.OnId_DestinationCityChanging(value);
					this.SendPropertyChanging();
					this._Id_DestinationCity = value;
					this.SendPropertyChanged("Id_DestinationCity");
					this.OnId_DestinationCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_DestinationZip", DbType="Int NOT NULL")]
		public int Id_DestinationZip
		{
			get
			{
				return this._Id_DestinationZip;
			}
			set
			{
				if ((this._Id_DestinationZip != value))
				{
					this.OnId_DestinationZipChanging(value);
					this.SendPropertyChanging();
					this._Id_DestinationZip = value;
					this.SendPropertyChanged("Id_DestinationZip");
					this.OnId_DestinationZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_RequestType", DbType="Int NOT NULL")]
		public int Id_RequestType
		{
			get
			{
				return this._Id_RequestType;
			}
			set
			{
				if ((this._Id_RequestType != value))
				{
					this.OnId_RequestTypeChanging(value);
					this.SendPropertyChanging();
					this._Id_RequestType = value;
					this.SendPropertyChanged("Id_RequestType");
					this.OnId_RequestTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_PartnerLocation", DbType="Int NOT NULL")]
		public int Id_PartnerLocation
		{
			get
			{
				return this._Id_PartnerLocation;
			}
			set
			{
				if ((this._Id_PartnerLocation != value))
				{
					this.OnId_PartnerLocationChanging(value);
					this.SendPropertyChanging();
					this._Id_PartnerLocation = value;
					this.SendPropertyChanged("Id_PartnerLocation");
					this.OnId_PartnerLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minimum", DbType="Money NOT NULL")]
		public decimal Minimum
		{
			get
			{
				return this._Minimum;
			}
			set
			{
				if ((this._Minimum != value))
				{
					this.OnMinimumChanging(value);
					this.SendPropertyChanging();
					this._Minimum = value;
					this.SendPropertyChanged("Minimum");
					this.OnMinimumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From1To4Pallets", DbType="Money NOT NULL")]
		public decimal From1To4Pallets
		{
			get
			{
				return this._From1To4Pallets;
			}
			set
			{
				if ((this._From1To4Pallets != value))
				{
					this.OnFrom1To4PalletsChanging(value);
					this.SendPropertyChanging();
					this._From1To4Pallets = value;
					this.SendPropertyChanged("From1To4Pallets");
					this.OnFrom1To4PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From5To8Pallets", DbType="Money NOT NULL")]
		public decimal From5To8Pallets
		{
			get
			{
				return this._From5To8Pallets;
			}
			set
			{
				if ((this._From5To8Pallets != value))
				{
					this.OnFrom5To8PalletsChanging(value);
					this.SendPropertyChanging();
					this._From5To8Pallets = value;
					this.SendPropertyChanged("From5To8Pallets");
					this.OnFrom5To8PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From9To12Pallets", DbType="Money NOT NULL")]
		public decimal From9To12Pallets
		{
			get
			{
				return this._From9To12Pallets;
			}
			set
			{
				if ((this._From9To12Pallets != value))
				{
					this.OnFrom9To12PalletsChanging(value);
					this.SendPropertyChanging();
					this._From9To12Pallets = value;
					this.SendPropertyChanged("From9To12Pallets");
					this.OnFrom9To12PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From13To16Pallets", DbType="Money NOT NULL")]
		public decimal From13To16Pallets
		{
			get
			{
				return this._From13To16Pallets;
			}
			set
			{
				if ((this._From13To16Pallets != value))
				{
					this.OnFrom13To16PalletsChanging(value);
					this.SendPropertyChanging();
					this._From13To16Pallets = value;
					this.SendPropertyChanged("From13To16Pallets");
					this.OnFrom13To16PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From17To20Pallets", DbType="Money NOT NULL")]
		public decimal From17To20Pallets
		{
			get
			{
				return this._From17To20Pallets;
			}
			set
			{
				if ((this._From17To20Pallets != value))
				{
					this.OnFrom17To20PalletsChanging(value);
					this.SendPropertyChanging();
					this._From17To20Pallets = value;
					this.SendPropertyChanged("From17To20Pallets");
					this.OnFrom17To20PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From21To24Pallets", DbType="Money NOT NULL")]
		public decimal From21To24Pallets
		{
			get
			{
				return this._From21To24Pallets;
			}
			set
			{
				if ((this._From21To24Pallets != value))
				{
					this.OnFrom21To24PalletsChanging(value);
					this.SendPropertyChanging();
					this._From21To24Pallets = value;
					this.SendPropertyChanged("From21To24Pallets");
					this.OnFrom21To24PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From25To28Pallets", DbType="Money NOT NULL")]
		public decimal From25To28Pallets
		{
			get
			{
				return this._From25To28Pallets;
			}
			set
			{
				if ((this._From25To28Pallets != value))
				{
					this.OnFrom25To28PalletsChanging(value);
					this.SendPropertyChanging();
					this._From25To28Pallets = value;
					this.SendPropertyChanged("From25To28Pallets");
					this.OnFrom25To28PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From29To32Pallets", DbType="Money NOT NULL")]
		public decimal From29To32Pallets
		{
			get
			{
				return this._From29To32Pallets;
			}
			set
			{
				if ((this._From29To32Pallets != value))
				{
					this.OnFrom29To32PalletsChanging(value);
					this.SendPropertyChanging();
					this._From29To32Pallets = value;
					this.SendPropertyChanged("From29To32Pallets");
					this.OnFrom29To32PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From33To36Pallets", DbType="Money NOT NULL")]
		public decimal From33To36Pallets
		{
			get
			{
				return this._From33To36Pallets;
			}
			set
			{
				if ((this._From33To36Pallets != value))
				{
					this.OnFrom33To36PalletsChanging(value);
					this.SendPropertyChanging();
					this._From33To36Pallets = value;
					this.SendPropertyChanged("From33To36Pallets");
					this.OnFrom33To36PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From37To40Pallets", DbType="Money NOT NULL")]
		public decimal From37To40Pallets
		{
			get
			{
				return this._From37To40Pallets;
			}
			set
			{
				if ((this._From37To40Pallets != value))
				{
					this.OnFrom37To40PalletsChanging(value);
					this.SendPropertyChanging();
					this._From37To40Pallets = value;
					this.SendPropertyChanged("From37To40Pallets");
					this.OnFrom37To40PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From41To44Pallets", DbType="Money NOT NULL")]
		public decimal From41To44Pallets
		{
			get
			{
				return this._From41To44Pallets;
			}
			set
			{
				if ((this._From41To44Pallets != value))
				{
					this.OnFrom41To44PalletsChanging(value);
					this.SendPropertyChanging();
					this._From41To44Pallets = value;
					this.SendPropertyChanged("From41To44Pallets");
					this.OnFrom41To44PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From45To48Pallets", DbType="Money NOT NULL")]
		public decimal From45To48Pallets
		{
			get
			{
				return this._From45To48Pallets;
			}
			set
			{
				if ((this._From45To48Pallets != value))
				{
					this.OnFrom45To48PalletsChanging(value);
					this.SendPropertyChanging();
					this._From45To48Pallets = value;
					this.SendPropertyChanged("From45To48Pallets");
					this.OnFrom45To48PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From49To52Pallets", DbType="Money NOT NULL")]
		public decimal From49To52Pallets
		{
			get
			{
				return this._From49To52Pallets;
			}
			set
			{
				if ((this._From49To52Pallets != value))
				{
					this.OnFrom49To52PalletsChanging(value);
					this.SendPropertyChanging();
					this._From49To52Pallets = value;
					this.SendPropertyChanged("From49To52Pallets");
					this.OnFrom49To52PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From53To56Pallets", DbType="Money NOT NULL")]
		public decimal From53To56Pallets
		{
			get
			{
				return this._From53To56Pallets;
			}
			set
			{
				if ((this._From53To56Pallets != value))
				{
					this.OnFrom53To56PalletsChanging(value);
					this.SendPropertyChanging();
					this._From53To56Pallets = value;
					this.SendPropertyChanged("From53To56Pallets");
					this.OnFrom53To56PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From57To60Pallets", DbType="Money NOT NULL")]
		public decimal From57To60Pallets
		{
			get
			{
				return this._From57To60Pallets;
			}
			set
			{
				if ((this._From57To60Pallets != value))
				{
					this.OnFrom57To60PalletsChanging(value);
					this.SendPropertyChanging();
					this._From57To60Pallets = value;
					this.SendPropertyChanged("From57To60Pallets");
					this.OnFrom57To60PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From61To64Pallets", DbType="Money NOT NULL")]
		public decimal From61To64Pallets
		{
			get
			{
				return this._From61To64Pallets;
			}
			set
			{
				if ((this._From61To64Pallets != value))
				{
					this.OnFrom61To64PalletsChanging(value);
					this.SendPropertyChanging();
					this._From61To64Pallets = value;
					this.SendPropertyChanged("From61To64Pallets");
					this.OnFrom61To64PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maximum", DbType="Money NOT NULL")]
		public decimal Maximum
		{
			get
			{
				return this._Maximum;
			}
			set
			{
				if ((this._Maximum != value))
				{
					this.OnMaximumChanging(value);
					this.SendPropertyChanging();
					this._Maximum = value;
					this.SendPropertyChanged("Maximum");
					this.OnMaximumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequencyLTL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShipmentFrequencyLTL
		{
			get
			{
				return this._ShipmentFrequencyLTL;
			}
			set
			{
				if ((this._ShipmentFrequencyLTL != value))
				{
					this.OnShipmentFrequencyLTLChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequencyLTL = value;
					this.SendPropertyChanged("ShipmentFrequencyLTL");
					this.OnShipmentFrequencyLTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTimeGroupage", DbType="Int NOT NULL")]
		public int TransitTimeGroupage
		{
			get
			{
				return this._TransitTimeGroupage;
			}
			set
			{
				if ((this._TransitTimeGroupage != value))
				{
					this.OnTransitTimeGroupageChanging(value);
					this.SendPropertyChanging();
					this._TransitTimeGroupage = value;
					this.SendPropertyChanged("TransitTimeGroupage");
					this.OnTransitTimeGroupageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTimeLTL", DbType="Int NOT NULL")]
		public int TransitTimeLTL
		{
			get
			{
				return this._TransitTimeLTL;
			}
			set
			{
				if ((this._TransitTimeLTL != value))
				{
					this.OnTransitTimeLTLChanging(value);
					this.SendPropertyChanging();
					this._TransitTimeLTL = value;
					this.SendPropertyChanged("TransitTimeLTL");
					this.OnTransitTimeLTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentsLTL", DbType="NVarChar(100)")]
		public string CommentsLTL
		{
			get
			{
				return this._CommentsLTL;
			}
			set
			{
				if ((this._CommentsLTL != value))
				{
					this.OnCommentsLTLChanging(value);
					this.SendPropertyChanging();
					this._CommentsLTL = value;
					this.SendPropertyChanged("CommentsLTL");
					this.OnCommentsLTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tons3_5", DbType="Money NOT NULL")]
		public decimal Tons3_5
		{
			get
			{
				return this._Tons3_5;
			}
			set
			{
				if ((this._Tons3_5 != value))
				{
					this.OnTons3_5Changing(value);
					this.SendPropertyChanging();
					this._Tons3_5 = value;
					this.SendPropertyChanged("Tons3_5");
					this.OnTons3_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTime3_5Tons", DbType="Int NOT NULL")]
		public int TransitTime3_5Tons
		{
			get
			{
				return this._TransitTime3_5Tons;
			}
			set
			{
				if ((this._TransitTime3_5Tons != value))
				{
					this.OnTransitTime3_5TonsChanging(value);
					this.SendPropertyChanging();
					this._TransitTime3_5Tons = value;
					this.SendPropertyChanged("TransitTime3_5Tons");
					this.OnTransitTime3_5TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequency3_5Tons", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShipmentFrequency3_5Tons
		{
			get
			{
				return this._ShipmentFrequency3_5Tons;
			}
			set
			{
				if ((this._ShipmentFrequency3_5Tons != value))
				{
					this.OnShipmentFrequency3_5TonsChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequency3_5Tons = value;
					this.SendPropertyChanged("ShipmentFrequency3_5Tons");
					this.OnShipmentFrequency3_5TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tons7_5", DbType="Money NOT NULL")]
		public decimal Tons7_5
		{
			get
			{
				return this._Tons7_5;
			}
			set
			{
				if ((this._Tons7_5 != value))
				{
					this.OnTons7_5Changing(value);
					this.SendPropertyChanging();
					this._Tons7_5 = value;
					this.SendPropertyChanged("Tons7_5");
					this.OnTons7_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequency7_5Tons", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShipmentFrequency7_5Tons
		{
			get
			{
				return this._ShipmentFrequency7_5Tons;
			}
			set
			{
				if ((this._ShipmentFrequency7_5Tons != value))
				{
					this.OnShipmentFrequency7_5TonsChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequency7_5Tons = value;
					this.SendPropertyChanged("ShipmentFrequency7_5Tons");
					this.OnShipmentFrequency7_5TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tons24", DbType="Money NOT NULL")]
		public decimal Tons24
		{
			get
			{
				return this._Tons24;
			}
			set
			{
				if ((this._Tons24 != value))
				{
					this.OnTons24Changing(value);
					this.SendPropertyChanging();
					this._Tons24 = value;
					this.SendPropertyChanged("Tons24");
					this.OnTons24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequency24Tons", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShipmentFrequency24Tons
		{
			get
			{
				return this._ShipmentFrequency24Tons;
			}
			set
			{
				if ((this._ShipmentFrequency24Tons != value))
				{
					this.OnShipmentFrequency24TonsChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequency24Tons = value;
					this.SendPropertyChanged("ShipmentFrequency24Tons");
					this.OnShipmentFrequency24TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTimeFTL", DbType="Int NOT NULL")]
		public int TransitTimeFTL
		{
			get
			{
				return this._TransitTimeFTL;
			}
			set
			{
				if ((this._TransitTimeFTL != value))
				{
					this.OnTransitTimeFTLChanging(value);
					this.SendPropertyChanging();
					this._TransitTimeFTL = value;
					this.SendPropertyChanged("TransitTimeFTL");
					this.OnTransitTimeFTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentsFTL", DbType="NVarChar(100)")]
		public string CommentsFTL
		{
			get
			{
				return this._CommentsFTL;
			}
			set
			{
				if ((this._CommentsFTL != value))
				{
					this.OnCommentsFTLChanging(value);
					this.SendPropertyChanging();
					this._CommentsFTL = value;
					this.SendPropertyChanged("CommentsFTL");
					this.OnCommentsFTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int NOT NULL")]
		public int Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PricesImport")]
	public partial class PricesImport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _LaneID;
		
		private string _LaneName;
		
		private string _OriginCountry;
		
		private string _OriginCity;
		
		private string _OriginZip;
		
		private string _DestinationCountry;
		
		private string _DestinationCity;
		
		private string _DestinationZip;
		
		private string _Direction;
		
		private string _PartnerLocation;
		
		private System.Nullable<int> _Minimum;
		
		private System.Nullable<int> _From1To4Pallets;
		
		private System.Nullable<int> _From5To8Pallets;
		
		private System.Nullable<int> _From9To12Pallets;
		
		private System.Nullable<int> _From13To16Pallets;
		
		private System.Nullable<int> _From17To20Pallets;
		
		private System.Nullable<int> _From21To24Pallets;
		
		private System.Nullable<int> _From25To28Pallets;
		
		private System.Nullable<int> _From29To32Pallets;
		
		private System.Nullable<int> _From33To36Pallets;
		
		private System.Nullable<int> _From37To40Pallets;
		
		private System.Nullable<int> _From41To44Pallets;
		
		private System.Nullable<int> _From45To48Pallets;
		
		private System.Nullable<int> _From49To52Pallets;
		
		private System.Nullable<int> _From53To56Pallets;
		
		private System.Nullable<int> _From57To60Pallets;
		
		private System.Nullable<int> _From61To64Pallets;
		
		private System.Nullable<int> _Maximum;
		
		private string _ShipmentFrequencyLTL;
		
		private System.Nullable<int> _TransitTimeGroupage;
		
		private System.Nullable<int> _TransitTimeLTL;
		
		private string _CommentsLTL;
		
		private System.Nullable<decimal> _Tons3_5;
		
		private System.Nullable<int> _TransitTime3_5Tons;
		
		private string _ShipmentFrequency3_5Tons;
		
		private System.Nullable<decimal> _Tons7_5;
		
		private string _ShipmentFrequency7_5Tons;
		
		private System.Nullable<decimal> _Tons24;
		
		private string _ShipmentFrequency24Tons;
		
		private System.Nullable<int> _TransitTimeFTL;
		
		private string _CommentsFTL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLaneIDChanging(string value);
    partial void OnLaneIDChanged();
    partial void OnLaneNameChanging(string value);
    partial void OnLaneNameChanged();
    partial void OnOriginCountryChanging(string value);
    partial void OnOriginCountryChanged();
    partial void OnOriginCityChanging(string value);
    partial void OnOriginCityChanged();
    partial void OnOriginZipChanging(string value);
    partial void OnOriginZipChanged();
    partial void OnDestinationCountryChanging(string value);
    partial void OnDestinationCountryChanged();
    partial void OnDestinationCityChanging(string value);
    partial void OnDestinationCityChanged();
    partial void OnDestinationZipChanging(string value);
    partial void OnDestinationZipChanged();
    partial void OnDirectionChanging(string value);
    partial void OnDirectionChanged();
    partial void OnPartnerLocationChanging(string value);
    partial void OnPartnerLocationChanged();
    partial void OnMinimumChanging(System.Nullable<int> value);
    partial void OnMinimumChanged();
    partial void OnFrom1To4PalletsChanging(System.Nullable<int> value);
    partial void OnFrom1To4PalletsChanged();
    partial void OnFrom5To8PalletsChanging(System.Nullable<int> value);
    partial void OnFrom5To8PalletsChanged();
    partial void OnFrom9To12PalletsChanging(System.Nullable<int> value);
    partial void OnFrom9To12PalletsChanged();
    partial void OnFrom13To16PalletsChanging(System.Nullable<int> value);
    partial void OnFrom13To16PalletsChanged();
    partial void OnFrom17To20PalletsChanging(System.Nullable<int> value);
    partial void OnFrom17To20PalletsChanged();
    partial void OnFrom21To24PalletsChanging(System.Nullable<int> value);
    partial void OnFrom21To24PalletsChanged();
    partial void OnFrom25To28PalletsChanging(System.Nullable<int> value);
    partial void OnFrom25To28PalletsChanged();
    partial void OnFrom29To32PalletsChanging(System.Nullable<int> value);
    partial void OnFrom29To32PalletsChanged();
    partial void OnFrom33To36PalletsChanging(System.Nullable<int> value);
    partial void OnFrom33To36PalletsChanged();
    partial void OnFrom37To40PalletsChanging(System.Nullable<int> value);
    partial void OnFrom37To40PalletsChanged();
    partial void OnFrom41To44PalletsChanging(System.Nullable<int> value);
    partial void OnFrom41To44PalletsChanged();
    partial void OnFrom45To48PalletsChanging(System.Nullable<int> value);
    partial void OnFrom45To48PalletsChanged();
    partial void OnFrom49To52PalletsChanging(System.Nullable<int> value);
    partial void OnFrom49To52PalletsChanged();
    partial void OnFrom53To56PalletsChanging(System.Nullable<int> value);
    partial void OnFrom53To56PalletsChanged();
    partial void OnFrom57To60PalletsChanging(System.Nullable<int> value);
    partial void OnFrom57To60PalletsChanged();
    partial void OnFrom61To64PalletsChanging(System.Nullable<int> value);
    partial void OnFrom61To64PalletsChanged();
    partial void OnMaximumChanging(System.Nullable<int> value);
    partial void OnMaximumChanged();
    partial void OnShipmentFrequencyLTLChanging(string value);
    partial void OnShipmentFrequencyLTLChanged();
    partial void OnTransitTimeGroupageChanging(System.Nullable<int> value);
    partial void OnTransitTimeGroupageChanged();
    partial void OnTransitTimeLTLChanging(System.Nullable<int> value);
    partial void OnTransitTimeLTLChanged();
    partial void OnCommentsLTLChanging(string value);
    partial void OnCommentsLTLChanged();
    partial void OnTons3_5Changing(System.Nullable<decimal> value);
    partial void OnTons3_5Changed();
    partial void OnTransitTime3_5TonsChanging(System.Nullable<int> value);
    partial void OnTransitTime3_5TonsChanged();
    partial void OnShipmentFrequency3_5TonsChanging(string value);
    partial void OnShipmentFrequency3_5TonsChanged();
    partial void OnTons7_5Changing(System.Nullable<decimal> value);
    partial void OnTons7_5Changed();
    partial void OnShipmentFrequency7_5TonsChanging(string value);
    partial void OnShipmentFrequency7_5TonsChanged();
    partial void OnTons24Changing(System.Nullable<decimal> value);
    partial void OnTons24Changed();
    partial void OnShipmentFrequency24TonsChanging(string value);
    partial void OnShipmentFrequency24TonsChanged();
    partial void OnTransitTimeFTLChanging(System.Nullable<int> value);
    partial void OnTransitTimeFTLChanged();
    partial void OnCommentsFTLChanging(string value);
    partial void OnCommentsFTLChanged();
    #endregion
		
		public PricesImport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneID", DbType="NVarChar(50)")]
		public string LaneID
		{
			get
			{
				return this._LaneID;
			}
			set
			{
				if ((this._LaneID != value))
				{
					this.OnLaneIDChanging(value);
					this.SendPropertyChanging();
					this._LaneID = value;
					this.SendPropertyChanged("LaneID");
					this.OnLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneName", DbType="NVarChar(50)")]
		public string LaneName
		{
			get
			{
				return this._LaneName;
			}
			set
			{
				if ((this._LaneName != value))
				{
					this.OnLaneNameChanging(value);
					this.SendPropertyChanging();
					this._LaneName = value;
					this.SendPropertyChanged("LaneName");
					this.OnLaneNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginCountry", DbType="NVarChar(50)")]
		public string OriginCountry
		{
			get
			{
				return this._OriginCountry;
			}
			set
			{
				if ((this._OriginCountry != value))
				{
					this.OnOriginCountryChanging(value);
					this.SendPropertyChanging();
					this._OriginCountry = value;
					this.SendPropertyChanged("OriginCountry");
					this.OnOriginCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginCity", DbType="NVarChar(50)")]
		public string OriginCity
		{
			get
			{
				return this._OriginCity;
			}
			set
			{
				if ((this._OriginCity != value))
				{
					this.OnOriginCityChanging(value);
					this.SendPropertyChanging();
					this._OriginCity = value;
					this.SendPropertyChanged("OriginCity");
					this.OnOriginCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginZip", DbType="NVarChar(50)")]
		public string OriginZip
		{
			get
			{
				return this._OriginZip;
			}
			set
			{
				if ((this._OriginZip != value))
				{
					this.OnOriginZipChanging(value);
					this.SendPropertyChanging();
					this._OriginZip = value;
					this.SendPropertyChanged("OriginZip");
					this.OnOriginZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationCountry", DbType="NVarChar(50)")]
		public string DestinationCountry
		{
			get
			{
				return this._DestinationCountry;
			}
			set
			{
				if ((this._DestinationCountry != value))
				{
					this.OnDestinationCountryChanging(value);
					this.SendPropertyChanging();
					this._DestinationCountry = value;
					this.SendPropertyChanged("DestinationCountry");
					this.OnDestinationCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationCity", DbType="NVarChar(50)")]
		public string DestinationCity
		{
			get
			{
				return this._DestinationCity;
			}
			set
			{
				if ((this._DestinationCity != value))
				{
					this.OnDestinationCityChanging(value);
					this.SendPropertyChanging();
					this._DestinationCity = value;
					this.SendPropertyChanged("DestinationCity");
					this.OnDestinationCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationZip", DbType="NVarChar(50)")]
		public string DestinationZip
		{
			get
			{
				return this._DestinationZip;
			}
			set
			{
				if ((this._DestinationZip != value))
				{
					this.OnDestinationZipChanging(value);
					this.SendPropertyChanging();
					this._DestinationZip = value;
					this.SendPropertyChanged("DestinationZip");
					this.OnDestinationZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direction", DbType="NVarChar(50)")]
		public string Direction
		{
			get
			{
				return this._Direction;
			}
			set
			{
				if ((this._Direction != value))
				{
					this.OnDirectionChanging(value);
					this.SendPropertyChanging();
					this._Direction = value;
					this.SendPropertyChanged("Direction");
					this.OnDirectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PartnerLocation", DbType="NVarChar(50)")]
		public string PartnerLocation
		{
			get
			{
				return this._PartnerLocation;
			}
			set
			{
				if ((this._PartnerLocation != value))
				{
					this.OnPartnerLocationChanging(value);
					this.SendPropertyChanging();
					this._PartnerLocation = value;
					this.SendPropertyChanged("PartnerLocation");
					this.OnPartnerLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Minimum", DbType="Int")]
		public System.Nullable<int> Minimum
		{
			get
			{
				return this._Minimum;
			}
			set
			{
				if ((this._Minimum != value))
				{
					this.OnMinimumChanging(value);
					this.SendPropertyChanging();
					this._Minimum = value;
					this.SendPropertyChanged("Minimum");
					this.OnMinimumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From1To4Pallets", DbType="Int")]
		public System.Nullable<int> From1To4Pallets
		{
			get
			{
				return this._From1To4Pallets;
			}
			set
			{
				if ((this._From1To4Pallets != value))
				{
					this.OnFrom1To4PalletsChanging(value);
					this.SendPropertyChanging();
					this._From1To4Pallets = value;
					this.SendPropertyChanged("From1To4Pallets");
					this.OnFrom1To4PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From5To8Pallets", DbType="Int")]
		public System.Nullable<int> From5To8Pallets
		{
			get
			{
				return this._From5To8Pallets;
			}
			set
			{
				if ((this._From5To8Pallets != value))
				{
					this.OnFrom5To8PalletsChanging(value);
					this.SendPropertyChanging();
					this._From5To8Pallets = value;
					this.SendPropertyChanged("From5To8Pallets");
					this.OnFrom5To8PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From9To12Pallets", DbType="Int")]
		public System.Nullable<int> From9To12Pallets
		{
			get
			{
				return this._From9To12Pallets;
			}
			set
			{
				if ((this._From9To12Pallets != value))
				{
					this.OnFrom9To12PalletsChanging(value);
					this.SendPropertyChanging();
					this._From9To12Pallets = value;
					this.SendPropertyChanged("From9To12Pallets");
					this.OnFrom9To12PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From13To16Pallets", DbType="Int")]
		public System.Nullable<int> From13To16Pallets
		{
			get
			{
				return this._From13To16Pallets;
			}
			set
			{
				if ((this._From13To16Pallets != value))
				{
					this.OnFrom13To16PalletsChanging(value);
					this.SendPropertyChanging();
					this._From13To16Pallets = value;
					this.SendPropertyChanged("From13To16Pallets");
					this.OnFrom13To16PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From17To20Pallets", DbType="Int")]
		public System.Nullable<int> From17To20Pallets
		{
			get
			{
				return this._From17To20Pallets;
			}
			set
			{
				if ((this._From17To20Pallets != value))
				{
					this.OnFrom17To20PalletsChanging(value);
					this.SendPropertyChanging();
					this._From17To20Pallets = value;
					this.SendPropertyChanged("From17To20Pallets");
					this.OnFrom17To20PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From21To24Pallets", DbType="Int")]
		public System.Nullable<int> From21To24Pallets
		{
			get
			{
				return this._From21To24Pallets;
			}
			set
			{
				if ((this._From21To24Pallets != value))
				{
					this.OnFrom21To24PalletsChanging(value);
					this.SendPropertyChanging();
					this._From21To24Pallets = value;
					this.SendPropertyChanged("From21To24Pallets");
					this.OnFrom21To24PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From25To28Pallets", DbType="Int")]
		public System.Nullable<int> From25To28Pallets
		{
			get
			{
				return this._From25To28Pallets;
			}
			set
			{
				if ((this._From25To28Pallets != value))
				{
					this.OnFrom25To28PalletsChanging(value);
					this.SendPropertyChanging();
					this._From25To28Pallets = value;
					this.SendPropertyChanged("From25To28Pallets");
					this.OnFrom25To28PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From29To32Pallets", DbType="Int")]
		public System.Nullable<int> From29To32Pallets
		{
			get
			{
				return this._From29To32Pallets;
			}
			set
			{
				if ((this._From29To32Pallets != value))
				{
					this.OnFrom29To32PalletsChanging(value);
					this.SendPropertyChanging();
					this._From29To32Pallets = value;
					this.SendPropertyChanged("From29To32Pallets");
					this.OnFrom29To32PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From33To36Pallets", DbType="Int")]
		public System.Nullable<int> From33To36Pallets
		{
			get
			{
				return this._From33To36Pallets;
			}
			set
			{
				if ((this._From33To36Pallets != value))
				{
					this.OnFrom33To36PalletsChanging(value);
					this.SendPropertyChanging();
					this._From33To36Pallets = value;
					this.SendPropertyChanged("From33To36Pallets");
					this.OnFrom33To36PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From37To40Pallets", DbType="Int")]
		public System.Nullable<int> From37To40Pallets
		{
			get
			{
				return this._From37To40Pallets;
			}
			set
			{
				if ((this._From37To40Pallets != value))
				{
					this.OnFrom37To40PalletsChanging(value);
					this.SendPropertyChanging();
					this._From37To40Pallets = value;
					this.SendPropertyChanged("From37To40Pallets");
					this.OnFrom37To40PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From41To44Pallets", DbType="Int")]
		public System.Nullable<int> From41To44Pallets
		{
			get
			{
				return this._From41To44Pallets;
			}
			set
			{
				if ((this._From41To44Pallets != value))
				{
					this.OnFrom41To44PalletsChanging(value);
					this.SendPropertyChanging();
					this._From41To44Pallets = value;
					this.SendPropertyChanged("From41To44Pallets");
					this.OnFrom41To44PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From45To48Pallets", DbType="Int")]
		public System.Nullable<int> From45To48Pallets
		{
			get
			{
				return this._From45To48Pallets;
			}
			set
			{
				if ((this._From45To48Pallets != value))
				{
					this.OnFrom45To48PalletsChanging(value);
					this.SendPropertyChanging();
					this._From45To48Pallets = value;
					this.SendPropertyChanged("From45To48Pallets");
					this.OnFrom45To48PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From49To52Pallets", DbType="Int")]
		public System.Nullable<int> From49To52Pallets
		{
			get
			{
				return this._From49To52Pallets;
			}
			set
			{
				if ((this._From49To52Pallets != value))
				{
					this.OnFrom49To52PalletsChanging(value);
					this.SendPropertyChanging();
					this._From49To52Pallets = value;
					this.SendPropertyChanged("From49To52Pallets");
					this.OnFrom49To52PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From53To56Pallets", DbType="Int")]
		public System.Nullable<int> From53To56Pallets
		{
			get
			{
				return this._From53To56Pallets;
			}
			set
			{
				if ((this._From53To56Pallets != value))
				{
					this.OnFrom53To56PalletsChanging(value);
					this.SendPropertyChanging();
					this._From53To56Pallets = value;
					this.SendPropertyChanged("From53To56Pallets");
					this.OnFrom53To56PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From57To60Pallets", DbType="Int")]
		public System.Nullable<int> From57To60Pallets
		{
			get
			{
				return this._From57To60Pallets;
			}
			set
			{
				if ((this._From57To60Pallets != value))
				{
					this.OnFrom57To60PalletsChanging(value);
					this.SendPropertyChanging();
					this._From57To60Pallets = value;
					this.SendPropertyChanged("From57To60Pallets");
					this.OnFrom57To60PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_From61To64Pallets", DbType="Int")]
		public System.Nullable<int> From61To64Pallets
		{
			get
			{
				return this._From61To64Pallets;
			}
			set
			{
				if ((this._From61To64Pallets != value))
				{
					this.OnFrom61To64PalletsChanging(value);
					this.SendPropertyChanging();
					this._From61To64Pallets = value;
					this.SendPropertyChanged("From61To64Pallets");
					this.OnFrom61To64PalletsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maximum", DbType="Int")]
		public System.Nullable<int> Maximum
		{
			get
			{
				return this._Maximum;
			}
			set
			{
				if ((this._Maximum != value))
				{
					this.OnMaximumChanging(value);
					this.SendPropertyChanging();
					this._Maximum = value;
					this.SendPropertyChanged("Maximum");
					this.OnMaximumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequencyLTL", DbType="NVarChar(50)")]
		public string ShipmentFrequencyLTL
		{
			get
			{
				return this._ShipmentFrequencyLTL;
			}
			set
			{
				if ((this._ShipmentFrequencyLTL != value))
				{
					this.OnShipmentFrequencyLTLChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequencyLTL = value;
					this.SendPropertyChanged("ShipmentFrequencyLTL");
					this.OnShipmentFrequencyLTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTimeGroupage", DbType="Int")]
		public System.Nullable<int> TransitTimeGroupage
		{
			get
			{
				return this._TransitTimeGroupage;
			}
			set
			{
				if ((this._TransitTimeGroupage != value))
				{
					this.OnTransitTimeGroupageChanging(value);
					this.SendPropertyChanging();
					this._TransitTimeGroupage = value;
					this.SendPropertyChanged("TransitTimeGroupage");
					this.OnTransitTimeGroupageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTimeLTL", DbType="Int")]
		public System.Nullable<int> TransitTimeLTL
		{
			get
			{
				return this._TransitTimeLTL;
			}
			set
			{
				if ((this._TransitTimeLTL != value))
				{
					this.OnTransitTimeLTLChanging(value);
					this.SendPropertyChanging();
					this._TransitTimeLTL = value;
					this.SendPropertyChanged("TransitTimeLTL");
					this.OnTransitTimeLTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentsLTL", DbType="NVarChar(50)")]
		public string CommentsLTL
		{
			get
			{
				return this._CommentsLTL;
			}
			set
			{
				if ((this._CommentsLTL != value))
				{
					this.OnCommentsLTLChanging(value);
					this.SendPropertyChanging();
					this._CommentsLTL = value;
					this.SendPropertyChanged("CommentsLTL");
					this.OnCommentsLTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tons3_5", DbType="Money")]
		public System.Nullable<decimal> Tons3_5
		{
			get
			{
				return this._Tons3_5;
			}
			set
			{
				if ((this._Tons3_5 != value))
				{
					this.OnTons3_5Changing(value);
					this.SendPropertyChanging();
					this._Tons3_5 = value;
					this.SendPropertyChanged("Tons3_5");
					this.OnTons3_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTime3_5Tons", DbType="Int")]
		public System.Nullable<int> TransitTime3_5Tons
		{
			get
			{
				return this._TransitTime3_5Tons;
			}
			set
			{
				if ((this._TransitTime3_5Tons != value))
				{
					this.OnTransitTime3_5TonsChanging(value);
					this.SendPropertyChanging();
					this._TransitTime3_5Tons = value;
					this.SendPropertyChanged("TransitTime3_5Tons");
					this.OnTransitTime3_5TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequency3_5Tons", DbType="NVarChar(50)")]
		public string ShipmentFrequency3_5Tons
		{
			get
			{
				return this._ShipmentFrequency3_5Tons;
			}
			set
			{
				if ((this._ShipmentFrequency3_5Tons != value))
				{
					this.OnShipmentFrequency3_5TonsChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequency3_5Tons = value;
					this.SendPropertyChanged("ShipmentFrequency3_5Tons");
					this.OnShipmentFrequency3_5TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tons7_5", DbType="Money")]
		public System.Nullable<decimal> Tons7_5
		{
			get
			{
				return this._Tons7_5;
			}
			set
			{
				if ((this._Tons7_5 != value))
				{
					this.OnTons7_5Changing(value);
					this.SendPropertyChanging();
					this._Tons7_5 = value;
					this.SendPropertyChanged("Tons7_5");
					this.OnTons7_5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequency7_5Tons", DbType="NVarChar(50)")]
		public string ShipmentFrequency7_5Tons
		{
			get
			{
				return this._ShipmentFrequency7_5Tons;
			}
			set
			{
				if ((this._ShipmentFrequency7_5Tons != value))
				{
					this.OnShipmentFrequency7_5TonsChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequency7_5Tons = value;
					this.SendPropertyChanged("ShipmentFrequency7_5Tons");
					this.OnShipmentFrequency7_5TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tons24", DbType="Money")]
		public System.Nullable<decimal> Tons24
		{
			get
			{
				return this._Tons24;
			}
			set
			{
				if ((this._Tons24 != value))
				{
					this.OnTons24Changing(value);
					this.SendPropertyChanging();
					this._Tons24 = value;
					this.SendPropertyChanged("Tons24");
					this.OnTons24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipmentFrequency24Tons", DbType="NVarChar(50)")]
		public string ShipmentFrequency24Tons
		{
			get
			{
				return this._ShipmentFrequency24Tons;
			}
			set
			{
				if ((this._ShipmentFrequency24Tons != value))
				{
					this.OnShipmentFrequency24TonsChanging(value);
					this.SendPropertyChanging();
					this._ShipmentFrequency24Tons = value;
					this.SendPropertyChanged("ShipmentFrequency24Tons");
					this.OnShipmentFrequency24TonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransitTimeFTL", DbType="Int")]
		public System.Nullable<int> TransitTimeFTL
		{
			get
			{
				return this._TransitTimeFTL;
			}
			set
			{
				if ((this._TransitTimeFTL != value))
				{
					this.OnTransitTimeFTLChanging(value);
					this.SendPropertyChanging();
					this._TransitTimeFTL = value;
					this.SendPropertyChanged("TransitTimeFTL");
					this.OnTransitTimeFTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentsFTL", DbType="NVarChar(50)")]
		public string CommentsFTL
		{
			get
			{
				return this._CommentsFTL;
			}
			set
			{
				if ((this._CommentsFTL != value))
				{
					this.OnCommentsFTLChanging(value);
					this.SendPropertyChanging();
					this._CommentsFTL = value;
					this.SendPropertyChanged("CommentsFTL");
					this.OnCommentsFTLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
