CREATE PROCEDURE [dbo].[spPrices_Insert]
    @Id_Transporter INT, 
    @LaneName NVARCHAR(100), 
    @Id_OriginCountry INT, 
    @Id_OriginCity INT, 
    @Id_OriginZip INT, 
    @Id_DestinationCountry INT, 
    @Id_DestinationCity INT, 
    @Id_DestinationZip INT, 
    @Id_RequestType INT, 
    @Id_PartnerLocation INT, 
    @Minimum MONEY, 
    @From1To4Pallets MONEY, 
    @From5To8Pallets MONEY, 
    @From9To12Pallets MONEY, 
    @From13To16Pallets MONEY, 
    @From17To20Pallets MONEY, 
    @From21To24Pallets MONEY, 
    @From25To28Pallets MONEY, 
    @From29To32Pallets MONEY, 
    @From33To36Pallets MONEY, 
    @From37To40Pallets MONEY, 
    @From41To44Pallets MONEY, 
    @From45To48Pallets MONEY, 
    @From49To52Pallets MONEY, 
    @From53To56Pallets MONEY, 
    @From57To60Pallets MONEY, 
    @From61To64Pallets MONEY, 
    @Maximum MONEY, 
    @ShipmentFrequencyLTL NVARCHAR(50), 
    @TransitTimeGroupage INT, 
    @TransitTimeLTL INT, 
    @CommentsLTL NVARCHAR(100), 
    @Tons3_5 MONEY, 
    @TransitTime3_5Tons INT, 
    @ShipmentFrequency3_5Tons NVARCHAR(50), 
    @Tons7_5 MONEY, 
    @ShipmentFrequency7_5Tons NVARCHAR(50), 
    @Tons24 MONEY, 
    @ShipmentFrequency24Tons NVARCHAR(50), 
    @TransitTimeFTL INT, 
    @CommentsFTL NVARCHAR(100), 
    @Active INT
AS
begin

	set nocount on;

	insert into dbo.[Prices](Id_Transporter, LaneName, Id_OriginCountry, Id_OriginCity, Id_OriginZip,
                             Id_DestinationCountry, Id_DestinationCity, Id_DestinationZip, Id_RequestType,
                             Id_PartnerLocation, Minimum, From1To4Pallets, From5To8Pallets, From9To12Pallets, 
                             From13To16Pallets, From17To20Pallets, From21To24Pallets, From25To28Pallets,
                             From29To32Pallets, From33To36Pallets, From37To40Pallets, From41To44Pallets, 
                             From45To48Pallets, From49To52Pallets, From53To56Pallets, From57To60Pallets, 
                             From61To64Pallets, Maximum, ShipmentFrequencyLTL, TransitTimeGroupage, 
                             TransitTimeLTL, CommentsLTL, Tons3_5, TransitTime3_5Tons, ShipmentFrequency3_5Tons,
                             Tons7_5, ShipmentFrequency7_5Tons, Tons24, ShipmentFrequency24Tons,
                             TransitTimeFTL, CommentsFTL, Active)
	values (  
    @Id_Transporter, 
    @LaneName, 
    @Id_OriginCountry, 
    @Id_OriginCity, 
    @Id_OriginZip, 
    @Id_DestinationCountry, 
    @Id_DestinationCity, 
    @Id_DestinationZip, 
    @Id_RequestType, 
    @Id_PartnerLocation, 
    @Minimum, 
    @From1To4Pallets , 
    @From5To8Pallets , 
    @From9To12Pallets , 
    @From13To16Pallets , 
    @From17To20Pallets, 
    @From21To24Pallets, 
    @From25To28Pallets, 
    @From29To32Pallets, 
    @From33To36Pallets, 
    @From37To40Pallets, 
    @From41To44Pallets, 
    @From45To48Pallets, 
    @From49To52Pallets, 
    @From53To56Pallets, 
    @From57To60Pallets, 
    @From61To64Pallets, 
    @Maximum , 
    @ShipmentFrequencyLTL, 
    @TransitTimeGroupage, 
    @TransitTimeLTL, 
    @CommentsLTL, 
    @Tons3_5, 
    @TransitTime3_5Tons, 
    @ShipmentFrequency3_5Tons, 
    @Tons7_5, 
    @ShipmentFrequency7_5Tons, 
    @Tons24, 
    @ShipmentFrequency24Tons, 
    @TransitTimeFTL, 
    @CommentsFTL, 
    @Active);

end