CREATE PROCEDURE [dbo].[spPrices_Update]
    @Id INT,
    @Minimum MONEY, 
    @From1To4Pallets MONEY, 
    @From5To8Pallets MONEY, 
    @From9To12Pallets MONEY, 
    @From13To16Pallets MONEY, 
    @From17To20Pallets MONEY, 
    @From21To24Pallets MONEY, 
    @From25To28Pallets MONEY, 
    @From29To32Pallets MONEY, 
    @From33To36Pallets MONEY, 
    @From37To40Pallets MONEY, 
    @From41To44Pallets MONEY, 
    @From45To48Pallets MONEY, 
    @From49To52Pallets MONEY, 
    @From53To56Pallets MONEY, 
    @From57To60Pallets MONEY, 
    @From61To64Pallets MONEY, 
    @Maximum MONEY, 
    @ShipmentFrequencyLTL NVARCHAR(50), 
    @TransitTimeGroupage INT, 
    @TransitTimeLTL INT, 
    @CommentsLTL NVARCHAR(100), 
    @Tons3_5 MONEY, 
    @TransitTime3_5Tons INT, 
    @ShipmentFrequency3_5Tons NVARCHAR(50), 
    @Tons7_5 MONEY, 
    @ShipmentFrequency7_5Tons NVARCHAR(50), 
    @Tons24 MONEY, 
    @ShipmentFrequency24Tons NVARCHAR(50), 
    @TransitTimeFTL INT, 
    @CommentsFTL NVARCHAR(100)
AS
begin

	set nocount on;

	update dbo.[Prices]
    set  [Prices].Minimum = @Minimum, 
         [Prices].From1To4Pallets = @From1To4Pallets, 
         [Prices].From5To8Pallets = @From5To8Pallets,
         [Prices].From9To12Pallets = @From9To12Pallets, 
         [Prices].From13To16Pallets = @From13To16Pallets, 
         [Prices].From17To20Pallets = @From17To20Pallets, 
         [Prices].From21To24Pallets = @From21To24Pallets, 
         [Prices].From25To28Pallets = @From25To28Pallets,   
         [Prices].From29To32Pallets = @From29To32Pallets, 
         [Prices].From33To36Pallets = @From33To36Pallets,
         [Prices].From37To40Pallets = @From37To40Pallets, 
         [Prices].From41To44Pallets = @From41To44Pallets,       
         [Prices].From45To48Pallets = @From45To48Pallets, 
         [Prices].From49To52Pallets = @From49To52Pallets, 
         [Prices].From53To56Pallets = @From53To56Pallets, 
         [Prices].From57To60Pallets = @From57To60Pallets,  
         [Prices].From61To64Pallets = @From61To64Pallets, 
         [Prices].Maximum = @Maximum, 
         [Prices].ShipmentFrequencyLTL = @ShipmentFrequencyLTL, 
         [Prices].TransitTimeGroupage = @TransitTimeGroupage,   
         [Prices].TransitTimeLTL = @TransitTimeLTL, 
         [Prices].CommentsLTL = @CommentsLTL, 
         [Prices].Tons3_5 = @Tons3_5, 
         [Prices].TransitTime3_5Tons = @TransitTime3_5Tons, 
         [Prices].ShipmentFrequency3_5Tons = @ShipmentFrequency3_5Tons,
         [Prices].Tons7_5 = @Tons7_5, 
         [Prices].ShipmentFrequency7_5Tons = @ShipmentFrequency7_5Tons,
         [Prices].Tons24 = @Tons24, 
         [Prices].ShipmentFrequency24Tons = @ShipmentFrequency24Tons, 
         [Prices].TransitTimeFTL = @TransitTimeFTL, 
         [Prices].CommentsFTL = @CommentsFTL
  where [Id] = @Id

end